services:
  - type: worker
    name: discord-attendance-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
